name: Pisek ⏳ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: ["3.11"]

    steps:
    - uses: actions/checkout@v4 
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4 # see https://docs.github.com/en/free-pro-team@latest/actions/guides/building-and-testing-python for more details
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Pisek
      run: |
        python -m pip install --upgrade pip
        pip install .
    - name: Test Pisek itself
      run: |
        ./tests.sh
    - name: Check formatting
      run: |
        pip install black
        black . --check
    - name: Check typing
      run: |
        pip install mypy
        pip install types-setuptools 
        pip install types-PyYAML
        pip install types-colorama
        mypy . --exclude fixtures
